### ISSUE TITLE
大大, 请问一下 `ocr_manager.m_task_id.qsize() != OCR_MAX_TASK_ID` 的作用

### ISSUE THREAD

**Issue by rongrong1000** [kanadeblisst00/wechat_ocr#11]
``` python
while ocr_manager.m_task_id.qsize() != OCR_MAX_TASK_ID:
        pass
```

我是一名其他语言的开发者, 并不擅长 python
想将该功能改造成http service
我会请求我的朋友帮助我, 不过在这之前我还想了解一下 这行代码的作用是做什么呢?

实在对不起 问了这么笨的问题

虽然我不懂, 但是我也可以推测一下
1. 等待所有队列中的任务完成后, 再退出
2. _________还没想出来_________

如果我猜的没错的话, 那 http service 是不是不用加这2句话

**Comment by kanadeblisst00** [comment]
你猜对了，它只是用来等待队列里任务都完成，防止进程还没识别完就退出，没有其他作用。如果有其他用于阻塞进程的代码，就可以不用加这两行

**Comment by rongrong1000** [comment]
明白了, 谢谢
